### ISSUE TITLE
Redirect triggers shutdown function, which emails REDCap admin and possibly disables the module

### ISSUE THREAD

**Issue by dr01d3r** [dr01d3r/redcap-em-orca-search#2]
https://github.com/dr01d3r/redcap-em-orca-search/blob/25f26df49350e6da3f2429c6513bc10ba6bd55e4/OrcaSearch.php#L38

**Comment by si-wehi** [comment]
Module functions as expected from my experience, the trigger does not disable it. Also seems to trigger the emails when you try to add a record.

**Comment by dr01d3r** [comment]
A patch is on the way that will remove the need to use the redirect function.

**Comment by dr01d3r** [comment]
The latest commit addresses this issue.  A submission to the repo is pending.
