### ISSUE TITLE
PHP8: REDCap crashed due to an unexpected PHP fatal error!

### ISSUE THREAD

**Issue by teigentler** [dr01d3r/redcap-em-orca-search#24]
REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/redcap/modules/orca_search_v2.3.3/traits/REDCapUtils.php:185 Stack trace: #0 /var/www/html/redcap/modules/orca_search_v2.3.3/traits/REDCapUtils.php(185): array_key_exists() #1 /var/www/html/redcap/modules/orca_search_v2.3.3/search.php(252): ORCA\OrcaSearch\OrcaSearch->getProjectRecordIds() #2 /var/www/html/redcap/redcap_v10.8.0/ExternalModules/index.php(121): require_once('...') #3 {main} thrown
File: /var/www/html/redcap/modules/orca_search_v2.3.3/traits/REDCapUtils.php
Line: 185

**Comment by dr01d3r** [comment]
Resolved through PR #26
