### ISSUE TITLE
ORCA Search REDCap

### ISSUE THREAD

**Issue by petermacisaac** [dr01d3r/redcap-em-orca-search#3]
I cant see what output occurs as a result of the following: Can you include a screen shot in the documentation  (am using REDCAP 8.3.0)
"Show instance badge
A red badge will display in the data table, indicating which instance the displayed value was found"

This extension is great.  I had also hoped to see it operational via a search link on the dashboard page to limit return of dashboard items to those meeting the search criteria.

Thanks great job

**Comment by dr01d3r** [comment]
I will attempt to add additional examples to the README for the instance badge functionality.
