### ISSUE TITLE
Feature Request: Ability to move the Open button to the left-hand side of the table

### ISSUE THREAD

**Issue by plitwin** [dr01d3r/redcap-em-orca-search#37]
We often have many columns in our search results. Would love to have the ability to move the Open button to the left-hand side of the table so users would not need to scroll to open the record. Or perhaps have the ability to automatically add a hyperlink to the record under the left-most column.

**Comment by dr01d3r** [comment]
Thanks @plitwin!  I will look into options for this.  If it were possible to something like a fixed "sticky" column, would you prefer something like that?  Here's an example from the library that we use.

https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html

**Comment by plitwin** [comment]
That looks good, Chris.
