### ISSUE TITLE
Redirect Add/Edit Records to Module

### ISSUE THREAD

**Issue by Dave2048** [dr01d3r/redcap-em-orca-search#4]
Excellent module, just what i wanted for a new project.
One minor glitch, when i tried to enable "Redirect Add/Edit Records to Module", i receive the following error: 
The 'hook_add_edit_records_page' hook did not complete for the 'orca_search' module because of the following error:

Unknown

The current user is a super user, so this module will be automatically disabled.

**Comment by dr01d3r** [comment]
Thanks for the report.  This has been addressed and will be released with the upcoming v1.2.0 update.
