### ISSUE TITLE
Orca doesn't work when any Advanced Custom Application Links are Enabled

### ISSUE THREAD

**Issue by plitwin** [dr01d3r/redcap-em-orca-search#9]
Chris,
I showed you the issue I was having at REDCapCon in Chicago. I then thought it was caused by a plug-in. But my cohort, David Rogers, dug into it and it appears that Orca will not work if any Custom Application Links of type Advanced are enabled. As soon as we disabled or deleted all the advanced custom application links, Orca started working.

**Comment by dr01d3r** [comment]
@plitwin I looked into Custom Application Links, and no variation of links cause any issues or interference with Orca Search.  What kind of links are you creating?

I would suggest someone review the custom plugin/hook we talked about at the conference.  You can send me a copy of that code if you like (my email is in my community site profile).

**Comment by dr01d3r** [comment]
@plitwin This has been resolved in v2.0.2 which was just released today.
